apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qjjskvesc-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-891ddb1302.4331.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:48fc13a80170328d7292166de3bfdbd2c86a213d@sha256:063f057125b52f879f788dd22ac848d1743dfddddfa4db34532ab02d86f6421d
          name: container-image
